"""Add public_id to Design retry 2

Revision ID: 57234a50dbd2
Revises: cb08736d0d9b
Create Date: 2025-12-12 10:55:22.063616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57234a50dbd2'
down_revision = 'cb08736d0d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_design_public_id', ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_constraint('uq_design_public_id', type_='unique')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
