"""add hashtags to design

Revision ID: bf0315a7e2ba
Revises: 57234a50dbd2
Create Date: 2025-12-15 10:47:10.780073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0315a7e2ba'
down_revision = '57234a50dbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashtags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_column('hashtags')

    # ### end Alembic commands ###
